openai:
  model: "gpt-4-turbo-preview"
  models:
    - "gpt-4-turbo-preview"
    - "gpt-4"
    - "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

news_api:
  language: "en"
  sort_by: "relevancy"
  page_size: 5

stock_analysis:
  prediction_threshold: 0.7
  confidence_threshold: 0.5
  max_stocks_per_batch: 10
  historical_data_days: 30
  rsi_periods: 14
  time_horizon_days: 90

recommendations:
  buy_threshold: 0.7
  sell_threshold: 0.3
  hold_threshold: 0.5 